# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96ef62f5726594809621d00b8f3d5b6cdcd7823a8abc6736bfc4b9944d3c246f8bb46ee4c244a3c7390c8f7725a0690f80c229fd7e5b2c4b94f097b0a2f38c30

test:
  secret_key_base: 908d779b5454daa449ca85af197b9b50875d1ef112fb151d5a99f2abdd5d2110379f3c9316d359440bb31e4399a4e3268153512cbf9e21fdf13820710769b5d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
